version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27020:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DATABASE_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_URL=mongodb+srv://crisp:crisp@crisp.gtgujyk.mongodb.net/?retryWrites=true&w=majority
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '80:8080'
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
