version: '3.3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_URL=mongodb://crisp:crisp@mongo:27017/crisp?authSource=admin&ssl=false
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - '80:8080'
    links:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - '27020:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DATABASE_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DATABASE_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 170.16.57.0/24
